name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HYPOTHESIS_PROFILE: CI

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install package
        run: |
          python -m pip install -e .[tests]

      - name: Cache Hypothesis database
        uses: actions/cache@v4
        id: cache-hypothesis
        with:
          path: .hypothesis
          key: hypothesis
          restore-keys: |
            hypothesis

      - name: Run tests
        run: |
          python -m pytest -v -m 'not todo' \
            --cov=neba --cov-branch --cov-report=xml \
            tests/config/test_section.py

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
